version: 2
jobs:
  buildAndTest:
    docker:
        - image: circleci/node
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Babel build
          command: npm run babel:build
      - run:
          name: Test
          command: npm test
      - run:
          name: Docker build
          command: docker build --no-cache .
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  publish:
    docker:
       - image: circleci/node
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Npm install
          command: npm install
      - run:
          name: Babel build
          command: npm run babel:build
      - run:
          name: Install Cantrips
          command: sudo npm i -g cantrips@"<=1.0.0"
      - run: 
          name: Npm credentials
          command: cantrips npm credentials
      - run:
          name: Npm publish
          command: npm publish

  
workflows:
  version: 2
  buildAndPublish:
    jobs:
      - buildAndTest:
          context: org-global
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - buildAndTest
          filters:
            tags:
              only: /^release-.*/
            branches:
              ignore: /.*/
          context: org-global

