version: 2
jobs:
  buildAndTest:
    docker:
      - image: circleci/node
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install yarn
          command: npm install yarn
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Babel build
          command: yarn run babel:build
      - run:
          name: Test
          command: yarn test:ci
      - store_test_results:
          path: test/junit
      - store_artifacts:
          path: test
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  publish:
    docker:
      - image: circleci/node
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install yarn
          command: npm install yarn
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Babel build
          command: yarn run babel:build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ./.npmrc

      - run:
          name: Npm publish
          command: yarn publish --access public

workflows:
  version: 2
  buildAndPublish:
    jobs:
      - buildAndTest:
          context: org-global
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - buildAndTest
          filters:
            tags:
              only: /^release-.*/
            branches:
              ignore: /.*/
          context: org-global
